lib/loany_web/router.ex
defmodule LoanyWeb.Router do
  use LoanyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Loany.Auth
  end

  scope "/", LoanyWeb do
    pipe_through :browser

    get "/", LoanApplicationController, :new
    get "/signin", SessionController, :new
    get "/signout", SessionController, :delete
    get "/notify", LoanApplicationController, :notify
    resources "/applications", LoanApplicationController, only: [:index, :show, :new, :create]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true
  end
end

lib/loany_web/controllers/session_controller.ex
defmodule LoanyWeb.SessionController do
  use LoanyWeb, :controller

  alias Loany.Accounts

  action_fallback(LoanyWeb.FallbackController)

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password}}) do
    with {:ok, user} <- Accounts.authenticate_by_email_password(email, password) do
      conn
      |> put_flash(:info, "User successfully logged in")
      |> put_session(:user_id, user.id)
      |> configure_session(renew: true)
      |> redirect(to: Routes.loan_application_path(conn, :index))
    end
  end

  def delete(conn, _) do
    conn
    |> configure_session(drop: true)
    |> put_flash(:success, "Successfuly signed out")
    |> redirect(to: "/")
  end
end

lib/loany_web/views/session_view.ex
defmodule LoanyWeb.SessionView do
  use LoanyWeb, :view
end

lib/loany_web/templates/session/new.html.eex
<div>
  <h1>Sign in</h1>

  <%= form_for @conn, Routes.session_path(@conn, :create), [method: :post, as: :user], fn f -> %>
    <div>
      <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
    </div>

    <div>
      <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    </div>

    <div>
      <%= submit "Sign in" %>
    </div>
  <% end %>
</div>