lib/loany_web/router.ex
defmodule LoanyWeb.Router do
  use LoanyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Loany.Auth
  end

  scope "/", LoanyWeb do
    pipe_through :browser

    get "/", LoanApplicationController, :new
    get "/signin", SessionController, :new
    get "/signout", SessionController, :delete
    get "/notify", LoanApplicationController, :notify
    resources "/applications", LoanApplicationController, only: [:index, :show, :new, :create]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true
  end
end

lib/loany_web/views/layout_view.ex
defmodule LoanyWeb.LayoutView do
  use LoanyWeb, :view
end

lib/loany_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Loany</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Loany", to: Routes.loan_application_path(@conn, :new) %></li>
            <%= if @current_user do %>
              <li><%= link "Signout", to: "/signout" %></li>
            <% else %>
              <li><%= link "Signin", to: "/signin" %></li>
            <% end %>
            <%= if @admin_user do %>
              <li><%= link "Applications", to: Routes.loan_application_path(@conn, :index) %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>